name: meedu_player
description: A new Flutter UI video controls for the flutter video_player plugin.
version: 0.2.0
homepage: https://github.com/darwin-morocho/flutter-meedu-player

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  video_player: ">=0.10.11 <2.0.0"
  flutter_spinkit: ">=4.0.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/meedu_player/assets/icons/play.png
    - packages/meedu_player/assets/icons/paused.png
    - packages/meedu_player/assets/icons/fullscreen-on.png
    - packages/meedu_player/assets/icons/fullscreen-off.png
    - packages/meedu_player/assets/icons/fast-forward.png
    - packages/meedu_player/assets/icons/fast-rewind.png
    - packages/meedu_player/assets/icons/repeat.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
